import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createServer as createHttpServer } from "node:http";
import { createServer } from "./server.js";
import { closeDb } from "@copilot-mem/shared";

const args = process.argv.slice(2);
const isHttp = args.includes("--http");
const isSetup = args.includes("setup");
const isGenerateInstructions = args.includes("generate-instructions");
const port = parseInt(
  args.find((a) => a.startsWith("--port="))?.split("=")[1] ?? "8787",
  10,
);

async function runSetup() {
  const { writeFileSync, existsSync, mkdirSync, readFileSync } = await import("node:fs");
  const { homedir } = await import("node:os");
  const { join } = await import("node:path");

  const configDir = join(homedir(), ".copilot");
  const configPath = join(configDir, "mcp-config.json");

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  let config: Record<string, unknown> = {};
  if (existsSync(configPath)) {
    config = JSON.parse(readFileSync(configPath, "utf-8"));
  }

  const mcpServers = (config.mcpServers as Record<string, unknown>) ?? {};
  mcpServers["copilot-mem"] = {
    type: "stdio",
    command: "npx",
    args: ["-y", "copilot-mem"],
  };
  config.mcpServers = mcpServers;

  writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n");
  console.log(`copilot-mem MCP server added to ${configPath}`);
  process.exit(0);
}

async function runGenerateInstructions() {
  const { writeFileSync, existsSync, mkdirSync } = await import("node:fs");
  const { join } = await import("node:path");
  const { getDb, getProjectName } = await import("@copilot-mem/shared");
  const { generateSessionContext } = await import("./context/index.js");

  const db = getDb({ readonly: true });
  const projectName = getProjectName();

  const sessionContext = generateSessionContext(db, projectName);

  const md = `# Project Context (auto-generated by copilot-mem)\n\n${sessionContext}\n`;

  const outDir = join(process.cwd(), ".github");
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const outPath = join(outDir, "copilot-instructions.md");
  writeFileSync(outPath, md);
  console.log(`Generated ${outPath} for project "${projectName}".`);
  closeDb();
  process.exit(0);
}

async function main() {
  if (isSetup) return runSetup();
  if (isGenerateInstructions) return runGenerateInstructions();

  const server = createServer();

  if (isHttp) {
    const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
    const httpServer = createHttpServer(async (req, res) => {
      if (req.method === "POST" && req.url === "/mcp") {
        await transport.handleRequest(req, res);
      } else {
        res.writeHead(404);
        res.end("Not found");
      }
    });

    await server.connect(transport);
    httpServer.listen(port, () => {
      console.error(`copilot-mem MCP server running on http://localhost:${port}/mcp`);
    });
  } else {
    const transport = new StdioServerTransport();
    await server.connect(transport);
    console.error("copilot-mem MCP server running on stdio");
  }

  process.on("SIGINT", () => {
    closeDb();
    process.exit(0);
  });

  process.on("SIGTERM", () => {
    closeDb();
    process.exit(0);
  });
}

main().catch((err) => {
  console.error("Fatal error:", err);
  closeDb();
  process.exit(1);
});
